// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhytoIntellect.Infrastructure.Presistence;

#nullable disable

namespace PhytoIntellect.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517223725_AddNotificationsTable")]
    partial class AddNotificationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhytoIntellect.Core.Entities.AiChatRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contraindications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HerbalistAverageRating")
                        .HasColumnType("real");

                    b.Property<int>("HerbalistTotalRatings")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainHerb")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("MatchPercentage")
                        .HasColumnType("float");

                    b.Property<string>("OtherPossibilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("RecommendedRecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("AiChatRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.AiRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<string>("CautionWarning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DiastolicBp")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("HasAllergies")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("bit");

                    b.Property<int>("HeartRateBpm")
                        .HasColumnType("int");

                    b.Property<double>("HeightCm")
                        .HasColumnType("float");

                    b.Property<float>("HerbalistAverageRating")
                        .HasColumnType("real");

                    b.Property<int>("HerbalistTotalRatings")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PreparationInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("RecommendedRecipeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SeverityScore")
                        .HasColumnType("int");

                    b.Property<int>("SymptomDurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystolicBp")
                        .HasColumnType("int");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("float");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("AiRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DiseaseType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSupportedByAi")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            DiseaseId = 1,
                            Description = "Habitual sleeplessness or inability to sleep.",
                            DiseaseName = "Insomnia",
                            DiseaseType = "Neurological",
                            IsSupportedByAi = false,
                            LanguageCode = "en",
                            Symptoms = "Difficulty falling asleep, waking up often."
                        },
                        new
                        {
                            DiseaseId = 2,
                            Description = "A common disorder that affects the large intestine.",
                            DiseaseName = "Irritable Bowel Syndrome (IBS)",
                            DiseaseType = "Gastrointestinal",
                            IsSupportedByAi = false,
                            LanguageCode = "en",
                            Symptoms = "Cramping, abdominal pain, bloating, gas."
                        },
                        new
                        {
                            DiseaseId = 3,
                            Description = "A viral infection of your nose and throat.",
                            DiseaseName = "Common Cold",
                            DiseaseType = "Respiratory",
                            IsSupportedByAi = false,
                            LanguageCode = "en",
                            Symptoms = "Runny nose, sore throat, cough, congestion."
                        },
                        new
                        {
                            DiseaseId = 4,
                            Description = "A feeling of worry, nervousness, or unease.",
                            DiseaseName = "Anxiety",
                            DiseaseType = "Psychological",
                            IsSupportedByAi = false,
                            LanguageCode = "en",
                            Symptoms = "Restlessness, rapid breathing, increased heart rate."
                        },
                        new
                        {
                            DiseaseId = 5,
                            Description = "Discomfort in your upper abdomen.",
                            DiseaseName = "Indigestion",
                            DiseaseType = "Gastrointestinal",
                            IsSupportedByAi = false,
                            LanguageCode = "en",
                            Symptoms = "Bloating, nausea, belching."
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("AiChatRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("AiRecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("RatingValue")
                        .HasColumnType("real");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("PatientId");

                    b.HasIndex("AiChatRecipeId", "PatientId")
                        .IsUnique()
                        .HasFilter("[AiChatRecipeId] IS NOT NULL");

                    b.HasIndex("AiRecipeId", "PatientId")
                        .IsUnique()
                        .HasFilter("[AiRecipeId] IS NOT NULL");

                    b.HasIndex("RecipeId", "PatientId")
                        .IsUnique()
                        .HasFilter("[RecipeId] IS NOT NULL");

                    b.ToTable("Feedbacks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Feedback_RatingValue", "[RatingValue] >= 1 AND [RatingValue] <= 5");

                            t.HasCheckConstraint("CK_Feedback_Target", "(CASE WHEN [RecipeId] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [AiRecipeId] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [AiChatRecipeId] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.Property<int>("HerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbId"));

                    b.Property<int?>("AddedByHerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HerbName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HerbId");

                    b.HasIndex("AddedByHerbalistId");

                    b.ToTable("Herbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.Property<int>("HerbalistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbalistId"));

                    b.Property<TimeSpan?>("AvailableFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AvailableTo")
                        .HasColumnType("time");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HerbalistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Herbalists");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistAiChatRecipe", b =>
                {
                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("AiChatRecipeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HerbalistId", "AiChatRecipeId");

                    b.HasIndex("AiChatRecipeId");

                    b.ToTable("HerbalistAiChatRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistAiRecipe", b =>
                {
                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("AiRecipeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HerbalistId", "AiRecipeId");

                    b.HasIndex("AiRecipeId");

                    b.ToTable("HerbalistAiRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistHerb", b =>
                {
                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("HerbalistId", "HerbId");

                    b.HasIndex("HerbId");

                    b.ToTable("HerbalistHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryId"));

                    b.Property<bool>("Asthma")
                        .HasColumnType("bit");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("KidneyDisease")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LiverDisease")
                        .HasColumnType("bit");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Pregnancy")
                        .HasColumnType("bit");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ExternalPaymentID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<decimal>("ItemsTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("PatientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderAiChatRecipe", b =>
                {
                    b.Property<int>("OrderAiChatRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderAiChatRecipeId"));

                    b.Property<int>("AiChatRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderAiChatRecipeId");

                    b.HasIndex("AiChatRecipeId");

                    b.HasIndex("SubOrderId");

                    b.ToTable("OrderAiChatRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderAiRecipe", b =>
                {
                    b.Property<int>("OrderAiRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderAiRecipeId"));

                    b.Property<int>("AiRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderAiRecipeId");

                    b.HasIndex("AiRecipeId");

                    b.HasIndex("SubOrderId");

                    b.ToTable("OrderAiRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderHerb", b =>
                {
                    b.Property<int>("OrderHerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderHerbId"));

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderHerbId");

                    b.HasIndex("HerbId");

                    b.HasIndex("SubOrderId");

                    b.ToTable("OrderHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderRecipe", b =>
                {
                    b.Property<int>("OrderRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderRecipeId"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SubOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderRecipeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SubOrderId");

                    b.ToTable("OrderRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("HerbalistId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeDisease", b =>
                {
                    b.Property<int>("RecipeDiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeDiseaseId"));

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeDiseaseId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeDiseases");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeHerb", b =>
                {
                    b.Property<int>("RecipeHerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeHerbId"));

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeHerbId");

                    b.HasIndex("HerbId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.ReviewRecipe", b =>
                {
                    b.Property<int>("ReviewRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewRecipeId"));

                    b.Property<int?>("AiChatRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("AiRecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("RatingValue")
                        .HasColumnType("real");

                    b.HasKey("ReviewRecipeId");

                    b.HasIndex("AiChatRecipeId");

                    b.HasIndex("HerbalistId");

                    b.HasIndex("AiRecipeId", "HerbalistId")
                        .IsUnique()
                        .HasFilter("[AiRecipeId] IS NOT NULL");

                    b.ToTable("ReviewRecipes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReviewRecipe_RatingValue", "[RatingValue] >= 1 AND [RatingValue] <= 5");
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.SubOrder", b =>
                {
                    b.Property<int>("SubOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubOrderId"));

                    b.Property<string>("ExternalDeliveryID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SubOrderId");

                    b.HasIndex("HerbalistId");

                    b.HasIndex("OrderId");

                    b.ToTable("SubOrders");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 999,
                            City = "Menofia",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "herbal.ai200@gmail.com",
                            FullName = "Super Admin",
                            Governorate = "Menofia",
                            IsEmailConfirmed = true,
                            PasswordHash = "$2a$12$uiBZ/NOR7RYt6xd.NBX.J./x.IlrlVx3IDp8GZQ3pstkzOckPTtLK",
                            Phone = "01000000000",
                            Role = "Admin",
                            Street = "Menofia",
                            UserName = "super_admin"
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TargetId", "Type")
                        .IsUnique();

                    b.ToTable("UserFavorites", (string)null);
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.AiChatRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.AiRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Feedback", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.AiChatRecipe", "AiChatRecipe")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AiChatRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhytoIntellect.Core.Entities.AiRecipe", "AiRecipe")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AiRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AiChatRecipe");

                    b.Navigation("AiRecipe");

                    b.Navigation("Patient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "AddedByHerbalist")
                        .WithMany()
                        .HasForeignKey("AddedByHerbalistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedByHerbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithOne("Herbalist")
                        .HasForeignKey("PhytoIntellect.Core.Entities.Herbalist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistAiChatRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.AiChatRecipe", "AiChatRecipe")
                        .WithMany("HerbalistInventories")
                        .HasForeignKey("AiChatRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany()
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiChatRecipe");

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistAiRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.AiRecipe", "AiRecipe")
                        .WithMany("HerbalistInventories")
                        .HasForeignKey("AiRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("HerbalistAiRecipes")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecipe");

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistHerb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herb", "Herb")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.MedicalHistory", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithOne("MedicalHistory")
                        .HasForeignKey("PhytoIntellect.Core.Entities.MedicalHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Notification", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Order", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderAiChatRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.AiChatRecipe", "AiChatRecipe")
                        .WithMany()
                        .HasForeignKey("AiChatRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.SubOrder", "SubOrder")
                        .WithMany("OrderAiChatRecipes")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiChatRecipe");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderAiRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.AiRecipe", "AiRecipe")
                        .WithMany()
                        .HasForeignKey("AiRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.SubOrder", "SubOrder")
                        .WithMany("OrderAiRecipes")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiRecipe");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderHerb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herb", "Herb")
                        .WithMany()
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.SubOrder", "SubOrder")
                        .WithMany("OrderHerbs")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.OrderRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.SubOrder", "SubOrder")
                        .WithMany("OrderRecipes")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("PhytoIntellect.Core.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("Recipes")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeDisease", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Disease", "Disease")
                        .WithMany("RecipeDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeDiseases")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeHerb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herb", "Herb")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.ReviewRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.AiChatRecipe", "AiChatRecipe")
                        .WithMany("HerbalistReviews")
                        .HasForeignKey("AiChatRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhytoIntellect.Core.Entities.AiRecipe", "AiRecipe")
                        .WithMany("HerbalistReviews")
                        .HasForeignKey("AiRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("ReviewRecipes")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiChatRecipe");

                    b.Navigation("AiRecipe");

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.SubOrder", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany()
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Order", "Order")
                        .WithMany("SubOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herbalist");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.UserFavorite", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.AiChatRecipe", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("HerbalistInventories");

                    b.Navigation("HerbalistReviews");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.AiRecipe", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("HerbalistInventories");

                    b.Navigation("HerbalistReviews");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Disease", b =>
                {
                    b.Navigation("RecipeDiseases");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.Navigation("HerbalistHerbs");

                    b.Navigation("RecipeHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.Navigation("HerbalistAiRecipes");

                    b.Navigation("HerbalistHerbs");

                    b.Navigation("Recipes");

                    b.Navigation("ReviewRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Order", b =>
                {
                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("RecipeDiseases");

                    b.Navigation("RecipeHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.SubOrder", b =>
                {
                    b.Navigation("OrderAiChatRecipes");

                    b.Navigation("OrderAiRecipes");

                    b.Navigation("OrderHerbs");

                    b.Navigation("OrderRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.User", b =>
                {
                    b.Navigation("Herbalist");

                    b.Navigation("Notifications");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
