// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhytoIntellect.Infrastructure.Presistence;

#nullable disable

namespace PhytoIntellect.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317225408_AddReviewRecipeAndHerbalistRatings")]
    partial class AddReviewRecipeAndHerbalistRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DiseaseType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            DiseaseId = 1,
                            Description = "Habitual sleeplessness or inability to sleep.",
                            DiseaseName = "Insomnia",
                            DiseaseType = "Neurological",
                            Symptoms = "Difficulty falling asleep, waking up often."
                        },
                        new
                        {
                            DiseaseId = 2,
                            Description = "A common disorder that affects the large intestine.",
                            DiseaseName = "Irritable Bowel Syndrome (IBS)",
                            DiseaseType = "Gastrointestinal",
                            Symptoms = "Cramping, abdominal pain, bloating, gas."
                        },
                        new
                        {
                            DiseaseId = 3,
                            Description = "A viral infection of your nose and throat.",
                            DiseaseName = "Common Cold",
                            DiseaseType = "Respiratory",
                            Symptoms = "Runny nose, sore throat, cough, congestion."
                        },
                        new
                        {
                            DiseaseId = 4,
                            Description = "A feeling of worry, nervousness, or unease.",
                            DiseaseName = "Anxiety",
                            DiseaseType = "Psychological",
                            Symptoms = "Restlessness, rapid breathing, increased heart rate."
                        },
                        new
                        {
                            DiseaseId = 5,
                            Description = "Discomfort in your upper abdomen.",
                            DiseaseName = "Indigestion",
                            DiseaseType = "Gastrointestinal",
                            Symptoms = "Bloating, nausea, belching."
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("RatingValue")
                        .HasColumnType("real");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RecipeId", "PatientId")
                        .IsUnique();

                    b.ToTable("Feedback", t =>
                        {
                            t.HasCheckConstraint("CK_Feedback_RatingValue", "[RatingValue] >= 1 AND [RatingValue] <= 5");
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.Property<int>("HerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbId"));

                    b.Property<int?>("AddedByHerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HerbName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ScientificName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HerbId");

                    b.HasIndex("AddedByHerbalistId");

                    b.ToTable("Herbs");

                    b.HasData(
                        new
                        {
                            HerbId = 1,
                            Benefits = "Relieves nausea, reduces inflammation, and aids digestion.",
                            Description = "A widely used root known for its spicy flavor and medicinal properties.",
                            Dosage = "1-3 grams daily",
                            HerbName = "Ginger",
                            IsApproved = true,
                            ScientificName = "Zingiber officinale",
                            Warnings = "High doses may cause heartburn or interact with blood thinners."
                        },
                        new
                        {
                            HerbId = 2,
                            Benefits = "Promotes sleep, reduces anxiety, and soothes stomach aches.",
                            Description = "A daisy-like plant commonly used to make herb infusions.",
                            Dosage = "1-2 cups of tea daily",
                            HerbName = "Chamomile",
                            IsApproved = true,
                            ScientificName = "Matricaria chamomilla",
                            Warnings = "May cause allergic reactions in people sensitive to ragweed."
                        },
                        new
                        {
                            HerbId = 3,
                            Benefits = "Powerful anti-inflammatory and antioxidant effects.",
                            Description = "A bright yellow spice widely used in Indian cuisine and Ayurvedic medicine.",
                            Dosage = "500-2000 mg daily (with black pepper)",
                            HerbName = "Turmeric",
                            IsApproved = true,
                            ScientificName = "Curcuma longa",
                            Warnings = "Can cause stomach upset in large amounts."
                        },
                        new
                        {
                            HerbId = 4,
                            Benefits = "Relieves irritable bowel syndrome (IBS), eases headaches, and clears congestion.",
                            Description = "A hybrid mint cross between watermint and spearmint.",
                            Dosage = "1-2 cups of tea or 0.2ml essential oil capsule",
                            HerbName = "Peppermint",
                            IsApproved = true,
                            ScientificName = "Mentha piperita",
                            Warnings = "May worsen acid reflux (GERD)."
                        },
                        new
                        {
                            HerbId = 5,
                            Benefits = "Boosts immune system, reduces blood pressure, and improves cholesterol levels.",
                            Description = "A pungent bulb used extensively in cooking and traditional medicine.",
                            Dosage = "1-2 cloves raw daily",
                            HerbName = "Garlic",
                            IsApproved = true,
                            ScientificName = "Allium sativum",
                            Warnings = "Bad breath, heartburn, and may increase bleeding risk."
                        },
                        new
                        {
                            HerbId = 6,
                            Benefits = "Reduces stress and cortisol levels, boosts brain function.",
                            Description = "An ancient medicinal herb classified as an adaptogen.",
                            Dosage = "300-500 mg root extract daily",
                            HerbName = "Ashwagandha",
                            IsApproved = true,
                            ScientificName = "Withania somnifera",
                            Warnings = "Not recommended for pregnant women or those with autoimmune diseases."
                        },
                        new
                        {
                            HerbId = 7,
                            Benefits = "Prevents and treats the common cold, boosts immunity.",
                            Description = "A flowering plant in the daisy family, popular for fighting flu.",
                            Dosage = "300-500 mg daily during illness",
                            HerbName = "Echinacea",
                            IsApproved = true,
                            ScientificName = "Echinacea purpurea",
                            Warnings = "May cause mild stomach upset or allergic reactions."
                        },
                        new
                        {
                            HerbId = 8,
                            Benefits = "Reduces anxiety, promotes restful sleep, and heals minor burns (topical).",
                            Description = "A fragrant purple flower known for its calming scent.",
                            Dosage = "1 cup of tea or aromatherapy",
                            HerbName = "Lavender",
                            IsApproved = true,
                            ScientificName = "Lavandula angustifolia",
                            Warnings = "Not recommended for young boys (hormonal effects) if used topically in large amounts."
                        },
                        new
                        {
                            HerbId = 9,
                            Benefits = "Increases energy, lowers blood sugar, and improves cognitive function.",
                            Description = "A slow-growing plant with fleshy roots, popular in Chinese medicine.",
                            Dosage = "200-400 mg daily",
                            HerbName = "Ginseng",
                            IsApproved = true,
                            ScientificName = "Panax ginseng",
                            Warnings = "Can cause insomnia or interact with diabetes medications."
                        },
                        new
                        {
                            HerbId = 10,
                            Benefits = "Improves memory and focus, promotes hair growth (topical).",
                            Description = "A fragrant evergreen herb native to the Mediterranean.",
                            Dosage = "1-2 cups of tea or used as a spice",
                            HerbName = "Rosemary",
                            IsApproved = true,
                            ScientificName = "Salvia rosmarinus",
                            Warnings = "Extremely high doses can trigger seizures."
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.Property<int>("HerbalistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbalistId"));

                    b.Property<TimeSpan?>("AvailableFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AvailableTo")
                        .HasColumnType("time");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HerbalistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Herbalists");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistHerb", b =>
                {
                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("HerbalistId", "HerbId");

                    b.HasIndex("HerbId");

                    b.ToTable("HerbalistHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryId"));

                    b.Property<bool>("Asthma")
                        .HasColumnType("bit");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("KidneyDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("LiverDisease")
                        .HasColumnType("bit");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Pregnancy")
                        .HasColumnType("bit");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.Property<bool>("CreatedByAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HerbalistAverageRating")
                        .HasColumnType("real");

                    b.Property<int?>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("HerbalistTotalRatings")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("HerbalistId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeDisease", b =>
                {
                    b.Property<int>("RecipeDiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeDiseaseId"));

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeDiseaseId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeDiseases");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeHerb", b =>
                {
                    b.Property<int>("RecipeHerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeHerbId"));

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeHerbId");

                    b.HasIndex("HerbId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.ReviewRecipe", b =>
                {
                    b.Property<int>("ReviewRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewRecipeId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("RatingValue")
                        .HasColumnType("real");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("ReviewRecipeId");

                    b.HasIndex("HerbalistId");

                    b.HasIndex("RecipeId", "HerbalistId")
                        .IsUnique();

                    b.ToTable("ReviewRecipe", t =>
                        {
                            t.HasCheckConstraint("CK_ReviewRecipe_RatingValue", "[RatingValue] >= 1 AND [RatingValue] <= 5");
                        });
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Feedback", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "AddedByHerbalist")
                        .WithMany()
                        .HasForeignKey("AddedByHerbalistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedByHerbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithOne("Herbalist")
                        .HasForeignKey("PhytoIntellect.Core.Entities.Herbalist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistHerb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herb", "Herb")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.MedicalHistory", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithOne("MedicalHistory")
                        .HasForeignKey("PhytoIntellect.Core.Entities.MedicalHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("PhytoIntellect.Core.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("Recipes")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeDisease", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Disease", "Disease")
                        .WithMany("RecipeDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeDiseases")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeHerb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herb", "Herb")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.ReviewRecipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("ReviewRecipes")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("Reviews")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herbalist");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Disease", b =>
                {
                    b.Navigation("RecipeDiseases");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.Navigation("HerbalistHerbs");

                    b.Navigation("RecipeHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.Navigation("HerbalistHerbs");

                    b.Navigation("Recipes");

                    b.Navigation("ReviewRecipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("RecipeDiseases");

                    b.Navigation("RecipeHerbs");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.User", b =>
                {
                    b.Navigation("Herbalist");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
