// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhytoIntellect.Infrastructure.Presistence;

#nullable disable

namespace PhytoIntellect.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312224812_AddMarketplaceEntities")]
    partial class AddMarketplaceEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.Property<int>("HerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbId"));

                    b.Property<int?>("AddedByHerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HerbName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ScientificName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HerbId");

                    b.HasIndex("AddedByHerbalistId");

                    b.ToTable("Herb");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.Property<int>("HerbalistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbalistId"));

                    b.Property<TimeSpan?>("AvailableFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AvailableTo")
                        .HasColumnType("time");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HerbalistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistHerb", b =>
                {
                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("HerbalistId", "HerbId");

                    b.HasIndex("HerbId");

                    b.ToTable("HerbalistHerb");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryId"));

                    b.Property<bool>("Asthma")
                        .HasColumnType("bit");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("KidneyDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("LiverDisease")
                        .HasColumnType("bit");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Pregnancy")
                        .HasColumnType("bit");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalHistory");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.Property<bool>("CreatedByAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("RecipeId");

                    b.HasIndex("HerbalistId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeHerb", b =>
                {
                    b.Property<int>("RecipeHerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeHerbId"));

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeHerbId");

                    b.HasIndex("HerbId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeHerb");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "AddedByHerbalist")
                        .WithMany()
                        .HasForeignKey("AddedByHerbalistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedByHerbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithOne("Herbalist")
                        .HasForeignKey("PhytoIntellect.Core.Entities.Herbalist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.HerbalistHerb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herb", "Herb")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.MedicalHistory", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Patient", "Patient")
                        .WithOne("MedicalHistory")
                        .HasForeignKey("PhytoIntellect.Core.Entities.MedicalHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("PhytoIntellect.Core.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herbalist", "Herbalist")
                        .WithMany("Recipes")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RecipeHerb", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.Herb", "Herb")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhytoIntellect.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("PhytoIntellect.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herb", b =>
                {
                    b.Navigation("HerbalistHerbs");

                    b.Navigation("RecipeHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Herbalist", b =>
                {
                    b.Navigation("HerbalistHerbs");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Patient", b =>
                {
                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeHerbs");
                });

            modelBuilder.Entity("PhytoIntellect.Core.Entities.User", b =>
                {
                    b.Navigation("Herbalist");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
